added preview command
rakkasjs/rakkasjs pull request #52
Opened 2022-09-15 07:14 UTC by sharmapukar217

allowing to run `yarn rakkas preview` :-)

2022-09-15 09:01 UTC, cyco130 requested changes
Hi!

Great! Thank you for this. I have a few suggestions for improvement. Maybe you can look at them?

Also, I don't understand why git hooks didn't run, the empty catch should have flagged an error and formatting should have been done automatically 🤔

2022-09-15 09:06 UTC, sharmapukar217 commented on packages/rakkasjs/src/cli/preview.ts
> +				listener(req, res)
static packages are served by vite using publicDir. I will check once again just to be sure

2022-09-15 09:10 UTC, cyco130 commented on packages/rakkasjs/src/cli/preview.ts
> +				listener(req, res)
Maybe they aren't because you removed the default handler?

2022-09-15 09:21 UTC, sharmapukar217 commented on packages/rakkasjs/src/cli/preview.ts
> +				listener(req, res)
oh yes. i'll check and use sirv if needed :-)

2022-09-15 09:22 UTC, sharmapukar217 commented on packages/rakkasjs/src/cli/preview.ts
> +	try {
i followed the same from serve.ts where the catch block was empty

2022-09-16 16:26 UTC, cyco130 commented
Great, we're almost there! Can you uncommit the yarn lock files though? Rakkas monirepo uses pnpm :)

2022-09-16 16:30 UTC, sharmapukar217 commented
> yarn

oh that was a mistake. I again switched to pnpm and yarn.lock was uncommitted later

2022-09-17 06:44 UTC, merged

2022-09-17 06:54 UTC, cyco130 commented
Thank you @sharmapukar217, it will be part of version 0.6.2. Already published in `rakkasjs@next` :)